[default]
path = "/home/ethan/Pictures/Wallpapers/"
duration = "10m"

[eDP-1]
path = "/home/ethan/Pictures/Wallpapers/"
duration = "10m"

[HDMI-A-1]
path = "/home/ethan/Pictures/Wallpapers/"
duration = "10m"
